import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import { Providers } from "@/components/Providers";
import { AppSidebar } from '@/components/AppSidebar';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR" className={inter.variable}>
      <body>
        <Providers>
          <div className="grid min-h-screen grid-cols-[250px_1fr] bg-muted/30">
            <AppSidebar />
            <main>{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
